// Login
export const LOGIN_ENABLE_LOADER = "LOGIN_ENABLE_LOADER";

export const LOGIN_DISABLE_LOADER = "LOGIN_DISABLE_LOADER";

export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_RESPONSE = "LOGIN_RESPONSE";

export const LOGIN_FAILED = "LOGIN_FAILED";

// SignUp
export const SIGNUP_ENABLE_LOADER = "SIGNUP_ENABLE_LOADER";

export const SIGNUP_DISABLE_LOADER = "SIGNUP_DISABLE_LOADER";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";

export const SIGNUP_LOADING_ENDED = "SIGNUP_LOADING_ENDED";

export const SIGNUP_FAILED = "SIGNUP_FAILED";

// forgotPassword

export const FORGOT_PASSWORD_ENABLE_LOADER = "FORGOT_PASSWORD_ENABLE_LOADER";

export const FORGOT_PASSWORD_DISABLE_LOADER = "FORGOT_PASSWORD_DISABLE_LOADER";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";

export const FORGOT_PASSWORD_RESPONSE = "FORGOT_PASSWORD_RESPONSE";

export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

// verifyOtp

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";

export const VERIFY_OTP_RESPONSE = "VERIFY_OTP_RESPONSE";

export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED";

// setPassword

export const SET_PASSWORD_REQUEST = "SET_PASSWORD_REQUEST";

export const SET_PASSWORD_RESPONSE = "SET_PASSWORD_RESPONSE";

export const SET_PASSWORD_FAILED = "SET_PASSWORD_FAILED";

//static

export const STATIC_ENABLE_LOADER = "STATIC_ENABLE_LOADER";

export const STATIC_DISABLE_LOADER = "STATIC_DISABLE_LOADER";

export const STATIC_REQUEST = "STATIC_REQUEST";

export const STATIC_RESPONSE = "STATIC_RESPONSE";

export const STATIC_FAILED = "STATIC_FAILED";
//person

export const PERSON_ENABLE_LOADER = "PERSON_ENABLE_LOADER";

export const PERSON_DISABLE_LOADER = "PERSON_DISABLE_LOADER";

export const PERSON_REQUEST = "PERSON_REQUEST";

export const PERSON_RESPONSE = "PERSON_RESPONSE";

export const PERSON_FAILED = "PERSON_FAILED";

//allPerson

export const ALL_PERSON_ENABLE_LOADER = "ALL_PERSON_ENABLE_LOADER";

export const ALL_PERSON_DISABLE_LOADER = "ALL_PERSON_DISABLE_LOADER";

export const ALL_PERSON_REQUEST = "ALL_PERSON_REQUEST";

export const ALL_PERSON_RESPONSE = "ALL_PERSON_RESPONSE";

export const ALL_PERSON_FAILED = "ALL_PERSON_FAILED";

//personDetails

export const PERSON_DETAILS_ENABLE_LOADER = "PERSON_DETAILS_ENABLE_LOADER";

export const PERSON_DETAILS_DISABLE_LOADER = "PERSON_DETAILS_DISABLE_LOADER";

export const PERSON_DETAILS_REQUEST = "PERSON_DETAILS_REQUEST";

export const PERSON_DETAILS_RESPONSE = "PERSON_DETAILS_RESPONSE";

export const PERSON_DETAILS_FAILED = "PERSON_DETAILS_FAILED";

//personSearch

export const PERSON_SEARCH_ENABLE_LOADER = "PERSON_SEARCH_ENABLE_LOADER";

export const PERSON_SEARCH_DISABLE_LOADER = "PERSON_SEARCH_DISABLE_LOADER";

export const PERSON_SEARCH_REQUEST = "PERSON_SEARCH_REQUEST";

export const PERSON_SEARCH_RESPONSE = "PERSON_SEARCH_RESPONSE";

export const PERSON_SEARCH_FAILED = "PERSON_SEARCH_FAILED";

//personClient

export const PERSON_CLIENT_ENABLE_LOADER = "PERSON_CLIENT_ENABLE_LOADER";

export const PERSON_CLIENT_DISABLE_LOADER = "PERSON_CLIENT_DISABLE_LOADER";

export const PERSON_CLIENT_REQUEST = "PERSON_CLIENT_REQUEST";

export const PERSON_CLIENT_RESPONSE = "PERSON_CLIENT_RESPONSE";

export const PERSON_CLIENT_FAILED = "PERSON_CLIENT_FAILED";

//personVendor

export const PERSON_VENDOR_ENABLE_LOADER = "PERSON_VENDOR_ENABLE_LOADER";

export const PERSON_VENDOR_DISABLE_LOADER = "PERSON_VENDOR_DISABLE_LOADER";

export const PERSON_VENDOR_REQUEST = "PERSON_VENDOR_REQUEST";

export const PERSON_VENDOR_RESPONSE = "PERSON_VENDOR_RESPONSE";

export const PERSON_VENDOR_FAILED = "PERSON_VENDOR_FAILED";

//company

export const COMPANY_ENABLE_LOADER = "COMPANY_ENABLE_LOADER";

export const COMPANY_DISABLE_LOADER = "COMPANY_DISABLE_LOADER";

export const COMPANY_REQUEST = "COMPANY_REQUEST";

export const COMPANY_RESPONSE = "COMPANY_RESPONSE";

export const COMPANY_FAILED = "COMPANY_FAILED";

//allCompany

export const ALL_COMPANY_ENABLE_LOADER = "ALL_COMPANY_ENABLE_LOADER";

export const ALL_COMPANY_DISABLE_LOADER = "ALL_COMPANY_DISABLE_LOADER";

export const ALL_COMPANY_REQUEST = "ALL_COMPANY_REQUEST";

export const ALL_COMPANY_RESPONSE = "ALL_COMPANY_RESPONSE";

export const ALL_COMPANY_FAILED = "ALL_COMPANY_FAILED";

//companyDetails

export const COMPANY_DETAILS_ENABLE_LOADER = "COMPANY_DETAILS_ENABLE_LOADER";

export const COMPANY_DETAILS_DISABLE_LOADER = "COMPANY_DETAILS_DISABLE_LOADER";

export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";

export const COMPANY_DETAILS_RESPONSE = "COMPANY_DETAILS_RESPONSE";

export const COMPANY_DETAILS_FAILED = "COMPANY_DETAILS_FAILED";

//companySearch

export const COMPANY_SEARCH_ENABLE_LOADER = "COMPANY_SEARCH_ENABLE_LOADER";

export const COMPANY_SEARCH_DISABLE_LOADER = "COMPANY_SEARCH_DISABLE_LOADER";

export const COMPANY_SEARCH_REQUEST = "COMPANY_SEARCH_REQUEST";

export const COMPANY_SEARCH_RESPONSE = "COMPANY_SEARCH_RESPONSE";

export const COMPANY_SEARCH_FAILED = "COMPANY_SEARCH_FAILED";

//userDetails

export const USERS_DETAILS_ENABLE_LOADER = "USERS_DETAILS_ENABLE_LOADER";

export const USERS_DETAILS_DISABLE_LOADER = "USERS_DETAILS_DISABLE_LOADER";

export const USERS_DETAILS_REQUEST = "USERS_DETAILS_REQUEST";

export const USERS_DETAILS_RESPONSE = "USERS_DETAILS_RESPONSE";

export const USERS_DETAILS_FAILED = "USERS_DETAILS_FAILED";

//position

export const POSITION_ENABLE_LOADER = "POSITION_ENABLE_LOADER";

export const POSITION_DISABLE_LOADER = "POSITION_DISABLE_LOADER";

export const POSITION_REQUEST = "POSITION_REQUEST";

export const POSITION_RESPONSE = "POSITION_RESPONSE";

export const POSITION_FAILED = "POSITION_FAILED";

//allPosition

export const ALL_POSITION_ENABLE_LOADER = "ALL_POSITION_ENABLE_LOADER";

export const ALL_POSITION_DISABLE_LOADER = "ALL_POSITION_DISABLE_LOADER";

export const ALL_POSITION_REQUEST = "ALL_POSITION_REQUEST";

export const ALL_POSITION_RESPONSE = "ALL_POSITION_RESPONSE";

export const ALL_POSITION_FAILED = "ALL_POSITION_FAILED";

//positionDetails

export const POSITION_DETAILS_ENABLE_LOADER = "POSITION_DETAILS_ENABLE_LOADER";

export const POSITION_DETAILS_DISABLE_LOADER =
  "POSITION_DETAILS_DISABLE_LOADER";

export const POSITION_DETAILS_REQUEST = "POSITION_DETAILS_REQUEST";

export const POSITION_DETAILS_RESPONSE = "POSITION_DETAILS_RESPONSE";

export const POSITION_DETAILS_FAILED = "POSITION_DETAILS_FAILED";

//positionSearch

export const POSITION_SEARCH_ENABLE_LOADER = "POSITION_SEARCH_ENABLE_LOADER";

export const POSITION_SEARCH_DISABLE_LOADER = "POSITION_SEARCH_DISABLE_LOADER";

export const POSITION_SEARCH_REQUEST = "POSITION_SEARCH_REQUEST";

export const POSITION_SEARCH_RESPONSE = "POSITION_SEARCH_RESPONSE";

export const POSITION_SEARCH_FAILED = "POSITION_SEARCH_FAILED";

//logout
export const LOG_OUT = "LOG_OUT";

export const LOGOUT_ENABLE_LOADER = "LOGOUT_ENABLE_LOADER";

export const LOGOUT_DISABLE_LOADER = "LOGOUT_DISABLE_LOADER";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";

export const LOGOUT_FAILED = "LOGOUT_FAILED";
